### PR TITLE
Merge of the repository of fatso83 (thanks !) before the transfer.

### PR DESCRIPTION
**Pull request by fatso83**
These are the changes I have done to make it run on Ubuntu and run backups (see discussion in #5). I have not tested them on a clean slate system.

### CODE REVIEW

**Comment by fatso83** [comment]
Back from the cycle trip?

**Comment by fatso83** [comment]
cool, I have deleted my repo.

**Comment by fatso83** [comment]
Still haven't seen any transfer request? Neither in notifications nor email

**Comment by leizh** [comment]
I restarted the transfer. Is it better ?

**Comment by fatso83** [comment]
Sorry for being an idiot, but I did get the transfer request after you restarted. Unfortunately, I also clicked the link after work the next day, and by that time it had expired. Could you restart it when it suits you (not in the weekend)?

**Comment by leizh** [comment]
I restarted it.

**Comment by fatso83** [comment]
Thank you. Finally found it in time 👍

**Comment by leizh** [comment]
_I_ do thank you.

**Pull request merged**
